# Generated by Django 4.1 on 2022-08-18 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('urlToImage', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('publishedAt', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.article')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
