# Generated by Django 4.1 on 2022-08-18 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0599909999 or 599999999'. Up to 10 digits allowed.", regex='(05|5)\\d{8}')])),
                ('national_id', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="national number must be entered in the format: '1999909999 or 2999999999'. Up to 10 digits allowed.", regex='(2|1)\\d{9}')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
